### PR TITLE
Dev .*(re)?run tests.*

### PR DESCRIPTION
**Pull request by mejs123**
.*(re)?run tests.*

### CODE REVIEW

**Comment by cocoy** [comment]
test

**Comment by mejs123** [comment]
Can one of the admins verify this patch?

**Comment by mejs123** [comment]
Can one of the admins verify this patch?

**Comment by mejs123** [comment]
Can one of the admins verify this patch?

**Comment by cocoy** [comment]
test

**Comment by mejs123** [comment]
Can one of the admins verify this patch?

**Comment by cocoy** [comment]
test this

**Comment by mejs123** [comment]
Can one of the admins verify this patch?

**Comment by cocoy** [comment]
test this

**Comment by mejs123** [comment]
Can one of the admins verify this patch?

**Comment by mejs123** [comment]
ok to test

**Comment by mejs123** [comment]
ok to test

**Comment by mejs123** [comment]
Can one of the admins verify this patch?

**Comment by cocoy** [comment]
test

**Pull request closed without merging**
